on:
  push:
    tags:
      - v*
name: Flutter Apk
jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: actions/subsito/flutter-action@v1
      with: flutter-version: '1.20.3'
    - run: flutter pub get
    - run: flutter build apk --split-per-abi
    - name: Release aok
      uses: ncipollo/release-action@v1
      with: 
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{secrets.TIMEAPP_TOKEN}}
