on:
  push:
    tags:
      - v*
name: Flutter Apk
jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.3'
    - run: flutter pub get
    - run: flutter build apk --split-per-abi
    - name: Release aok
      uses: ncipollo/release-action@v1
      with: 
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{secrets.TIMEAPP_TOKEN}}
    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{ secrets.FIREBASE_ANDROID_APPID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: testers
        file: build/app/outputs/apk/release/app-x86_64-release.apk
